language: python
python: 2.7
sudo: required
dist: bionic
arch: arm64
env:
  global:
    - TAG=${TAG:-latest}
    - BRANCH=master
    - DOCKER_NAME=centos-binary-neutron-openvswitch-agent-${BRANCH}-aarch64
    - DOCKER_VERSION=latest

services:
  - docker

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

script:
  - env
  - sudo docker run -di --name ovs_agent_docker -v $(pwd):/neutron-openvswitch-agent-builder -v /var/run/docker.sock:/var/run/docker.sock arm64v8/centos:7 /usr/sbin/init
  - sudo docker exec -i ovs_agent_docker uname -a
  - sudo docker exec -i ovs_agent_docker cat /etc/redhat-release

# Install prereqs
  - sudo docker exec -i ovs_agent_docker yum install -y git python3

# Install TripleO
  - git clone https://github.com/openstack/tripleo-repos $(pwd)/tripleo-repos
  - sudo docker exec -i ovs_agent_docker bash -cx 'cd /neutron-openvswitch-agent-builder/tripleo-repos; python3 ./setup.py install; pip3 install -r requirements.txt' || travis_terminate 1
  - sudo docker exec -i ovs_agent_docker tripleo-repos -d centos7 -b $BRANCH current

# Install kolla
  - sudo docker exec -i ovs_agent_docker yum install -y openstack-kolla || travis_terminate 1

# Create Docker
  - sudo docker exec -i ovs_agent_docker /usr/local/bin/kolla-build --base centos --base-arch aarch64 neutron-openvswitch-agent || travis_terminate 1

# Upload docker
  - docker_uuid=$(docker images|grep binary-neutron-openvswitch-agent|awk '{print $3}')

# Validate neutron version
  - docker run --rm $docker_uuid rpm -qa|sort|egrep 'neutron|os-vif'

# Tag docker
  - docker tag $docker_uuid mellanox/${DOCKER_NAME}:${DOCKER_VERSION}
  - docker images

deploy:
  # Push image to Dockerhub on merge to $BRANCH
  - provider: script
    skip_cleanup: true
    script: docker push mellanox/${DOCKER_NAME}:${DOCKER_VERSION}
    on:
      branch: $BRANCH
