language: python
python: 2.7
sudo: required
dist: bionic
arch: arm64
env:
  global:
    - TAG=${TAG:-latest}
    - BRANCH=stein
    - DOCKER_NAME=centos-binary-neutron-openvswitch-agent-${BRANCH}-aarch64
    - DOCKER_VERSION=latest

services:
  - docker

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

script:
  - env
  - sudo docker pull arm64v8/centos:7
  - sudo docker run -di --name ovs_agent_docker -v $(pwd):/neutron-openvswitch-agent-builder -v /var/run/docker.sock:/var/run/docker.sock arm64v8/centos:7 /usr/sbin/init
  - sudo docker exec -i ovs_agent_docker uname -a
  - sudo docker exec -i ovs_agent_docker cat /etc/redhat-release

# Install prereqs
  - sudo docker exec -i ovs_agent_docker bash -cx 'curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python2 ./get-pip.py'
  - sudo docker exec -i ovs_agent_docker bash -cx 'pip install setuptools tox pbr jinja2 requests'
  - sudo docker exec -i ovs_agent_docker bash -cx 'yum update -y'
  - sudo docker exec -i ovs_agent_docker bash -cx "yum install -y git"

# Install TripleO
  - git clone https://github.com/openstack/tripleo-repos $(pwd)/tripleo-repos
  - sudo docker exec -i ovs_agent_docker bash -cx 'cd /neutron-openvswitch-agent-builder/tripleo-repos; python2 ./setup.py install' || travis_terminate 1
  - sudo docker exec -i ovs_agent_docker tripleo-repos -d centos7 -b $BRANCH current

# Download Kolla
  - git clone -b stable/$BRANCH --single-branch https://github.com/openstack/kolla $(pwd)/kolla

# Patch Kolla
  - cp $TRAVIS_BUILD_DIR/*.patch $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/
  # this code will be replaced
  - sed -i 's/{% block neutron_openvswitch_agent_footer %}{% endblock %}//g' $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - sed -i 's/USER neutron//g' $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "{% block neutron_openvswitch_agent_footer %}" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2

  # add custom patch
  - echo "RUN (yum update -y)" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "RUN (yum install patch -y)" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "COPY 586252.patch /lib/python2.7/site-packages" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "COPY 698336.patch /lib/python2.7/site-packages" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "RUN (cd /lib/python2.7/site-packages; patch --verbose -p1 < 586252.patch)" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "RUN (cd /lib/python2.7/site-packages; patch --verbose -p0 < 698336.patch)" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2

  # return user neutron
  - echo "{% endblock %}" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2
  - echo "USER neutron" >> $(pwd)/kolla/docker/neutron/neutron-openvswitch-agent/Dockerfile.j2

# Install kolla
  - sudo docker exec -i ovs_agent_docker bash -cx 'cd /neutron-openvswitch-agent-builder/kolla; pip install -r requirements.txt; python2 ./setup.py install' || travis_terminate 1

# Create Docker
  - sudo docker exec -i ovs_agent_docker kolla-build --base centos --base-arch aarch64 neutron-openvswitch-agent || travis_terminate 1

# Upload docker
  - docker_uuid=$(docker images|grep binary-neutron-openvswitch-agent|awk '{print $3}')

# Validate neutron version
  - docker run --rm $docker_uuid rpm -qa|sort|egrep 'neutron|os-vif'

# Tag docker
  - docker tag $docker_uuid mellanox/${DOCKER_NAME}:${DOCKER_VERSION}
  - docker images

deploy:
  # Push image to Dockerhub on merge to $BRANCH
  - provider: script
    skip_cleanup: true
    script: >
      bash -cx '
      docker push mellanox/${DOCKER_NAME}:${DOCKER_VERSION};
      echo done'
    on:
      branch: $BRANCH
